name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          
      - name: chmod +x
        run: chmod +x ./gradlew
        
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set variables
        run: |
          {
            echo "version=v$(grep versionName app/build.gradle | awk -F\" '{print $2}')"
            echo "commit=$(echo ${{ github.sha }} | cut -c-7)"
            echo "repo=$(echo ${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/})"
            echo "timestamp=$(TZ='Asia/Tokyo' date +'%Y%m%d%H%M%S')"
            echo "name=${repo}-${version}-${commit}-${timestamp}"
          } >> $GITHUB_ENV

      - name: Show set variables
        run: |
          echo "name=${{ env.repo }}-${{ env.version }}-${{ env.commit }}-${{ env.timestamp }}" >> $GITHUB_ENV
          echo -e "version=${{ env.version }}"
          echo -e "commit=${{ env.commit }}"
          echo -e "repo=${{ env.repo }}"
          echo -e "timestamp=${{ env.timestamp }}"

      - name: Build
        run: |
          ./gradlew --no-daemon --stacktrace --warning-mode=all assembleRelease
          mv -vf app/build/outputs/apk/release/app-release.apk "${{ env.name }}.apk"

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.name }}"
          path: "${{ env.name }}.apk"
